### ISSUE TITLE
Мутирующие методы

### ISSUE THREAD

**Issue by octav47** [KpecToHoceLL/Project#11]
https://github.com/KpecToHoceLL/Project/blob/593eaa34837f91f77d20cd0772df8b32d1d674db/script.js#L30

Не рекомендую использовать мутирующие (то есть изменяющие значения переменной) методы

К ним относятся, кроме unshift, например splice, shift, pop

Подумай, как можно переписать эту часть кода без unshift, например, используя slice (не splice!) и spread-оператор (...array)

**Comment by KpecToHoceLL** [comment]
let trArray = ([buyName, price, buyTarget] = chosenMonth[key].split(","));
    trArray.unshift(date);
    
заменил на:
        let trArray = [date].concat(
      ([buyName, price, buyTarget] = chosenMonth[key].split(","))
    );
